export const ACTION_TYPES = {
	SET_USER: "SET_USER",
	LOGOUT: "LOGOUT",
	SET_POST_DATA: "SET_POST_DATA",
	OPEN_MODAL: "OPEN_MODAL",
	CLOSE_MODAL: "CLOSE_MODAL",
	RESET_POSTS_DATA: "RESET_POSTS_DATA",
};
